### ISSUE TITLE
Undefined variable $product

### ISSUE THREAD

**Issue by tomwesterling** [bootscore/bs-swiper#37]
Hey there,

I think this is a really cool plugin so I am trying to use it on my site. Unfortunately, I cannot make it work. I am calling a shortcode in my front-page.php file:

`<?php echo do_shortcode('[bs-swiper-card-product posts="4"]'); ?>`

My expectation was, that four products (in whatever selection and order) are displayed as sliders. However, I can only see a PHP warning:

> Warning: Undefined variable $product in /Users/tom/Local Sites/bootscore/app/public/wp-content/plugins/bs-swiper-main/templates/sc-swiper-card-product.php on line 51
> class="swiper-slide card h-auto mb-5 d-flex text-center product-card">

...follwed by an "fatal error":

> Fatal error: Uncaught Error: Call to a member function is_on_sale() on null in /Users/tom/Local Sites/bootscore/app/public/wp-content/plugins/woocommerce/templates/loop/sale-flash.php:25   ...

Did I miss some step before it can work? 

Thankful for any advice.

Cheers,
Tom

**Comment by crftwrk** [comment]
Hi Tom,

this is fixed here https://github.com/bootscore/bs-swiper/pull/33 and merged already. Release is next week, but you can download and install latest main branch. 

However, it seems that you have set the WP_DEBUG to true in your wp-config.php. If so, set this to false and ignore error.

Basti

**Comment by tomwesterling** [comment]
Hi Basti,

thank you for the fast reply!

I downloaded the latest main branch and re-installed the plugin. The warning "undefined variable $product" indeed disappeared, but the fatal error still remains. Here is the complete error description:

> [Fatal error: Uncaught Error: Call to a member function is_on_sale() on null in /Users/tom/Local Sites/bootscore/app/public/wp-content/plugins/woocommerce/templates/loop/sale-flash.php:25 Stack trace: #0 /Users/tom/Local Sites/bootscore/app/public/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include() #1 /Users/tom/Local Sites/bootscore/app/public/wp-content/plugins/woocommerce/includes/wc-template-functions.php(1422): wc_get_template('loop/sale-flash...') #2 /Users/tom/Local Sites/bootscore/app/public/wp-includes/class-wp-hook.php(308): woocommerce_show_product_loop_sale_flash('') #3 /Users/tom/Local Sites/bootscore/app/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #4 /Users/tom/Local Sites/bootscore/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #5 /Users/tom/Local Sites/bootscore/app/public/wp-content/plugins/bs-swiper-main/templates/sc-swiper-card-product.php(67): do_action('woocommerce_bef...') #6 /Users/tom/Local Sites/bootscore/app/public/wp-includes/shortcodes.php(355): bootscore_product_slider(Array, '', 'bs-swiper-card-...') #7 [internal function]: do_shortcode_tag(Array) #8 /Users/tom/Local Sites/bootscore/app/public/wp-includes/shortcodes.php(227): preg_replace_callback('/\\[(\\[?)(bs\\-sw...', 'do_shortcode_ta...', '[bs-swiper-card...') #9 /Users/tom/Local Sites/bootscore/app/public/wp-includes/class-wp-hook.php(308): do_shortcode('[bs-swiper-card...') #10 /Users/tom/Local Sites/bootscore/app/public/wp-includes/plugin.php(205): WP_Hook->apply_filters('[bs-swiper-card...', Array) #11 /Users/tom/Local Sites/bootscore/app/public/wp-content/plugins/woocommerce/includes/wc-formatting-functions.php(1121): apply_filters('woocommerce_sho...', '<!-- wp:shortco...') #12 /Users/tom/Local Sites/bootscore/app/public/wp-content/plugins/woocommerce/includes/wc-template-functions.php(1330): wc_format_content('<!-- wp:shortco...') #13 /Users/tom/Local Sites/bootscore/app/public/wp-includes/class-wp-hook.php(308): woocommerce_product_archive_description('') #14 /Users/tom/Local Sites/bootscore/app/public/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #15 /Users/tom/Local Sites/bootscore/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #16 /Users/tom/Local Sites/bootscore/app/public/wp-content/plugins/woocommerce/includes/wc-template-functions.php(989): do_action('woocommerce_arc...') #17 /Users/tom/Local Sites/bootscore/app/public/wp-content/themes/bootscore-main/woocommerce.php(31): woocommerce_content() #18 /Users/tom/Local Sites/bootscore/app/public/wp-includes/template-loader.php(106): include('/Users/tom/Loca...') #19 /Users/tom/Local Sites/bootscore/app/public/wp-blog-header.php(19): require_once('/Users/tom/Loca...') #20 /Users/tom/Local Sites/bootscore/app/public/index.php(17): require('/Users/tom/Loca...') #21 {main} thrown in /Users/tom/Local Sites/bootscore/app/public/wp-content/plugins/woocommerce/templates/loop/sale-flash.php on line 25](http://localhost:10008/hello-world/)

Also, I have checked that WB_DEBIG is defined as false. At least, my wp-config.php begins with

`if ( ! defined( 'WP_DEBUG' ) ) {
	define( 'WP_DEBUG', false );
}
`

Thanks for any further assistance.

Best,

Tom

**Comment by tomwesterling** [comment]
Edit: I think it was my mistake! It works now, if I add the category filter tag. So I guess it is required to specify categories to show.

**Comment by crftwrk** [comment]
Usually there should be no issues echo the shortcode in php files. Have you tried to add product shortcode on a block first with all parameters as described here https://bootscore.me/documentation/bs-swiper/#WooCommerce_Products ?

**Comment by crftwrk** [comment]
> Edit: I think it was my mistake! It works now, if I add the category filter tag. So I guess it is required to specify categories to show.

ok ;-)
